# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-crud-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-crud-api
  template:
    metadata:
      labels:
        app: go-crud-api
    spec:
      containers:
      - name: go-crud-api
        image: go-crud-api:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: go-crud-api
spec:
  selector:
    app: go-crud-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
